apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-python
spec:
  selector:
    matchLabels:
      app: eks-python
  replicas: 1 
  template: 
    metadata:
      labels:
        app: eks-python
    spec:
      containers:
      - name: eks-python
        image: 57c96ca7b552be3b69b57607c7ae406ae9f209fca2c69801189e79f1c1e5d14b
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eks-python
spec:
  type: LoadBalancer
  selector:
    app: eks-python
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
