apiVersion: myapps/v1
kind: Deployment
metadata:
  name: eks-python
spec:
  selector:
    matchLabels:
      app: eks-python
  replicas: 1 
  template: 
    metadata:
      labels:
        app: eks-python
    spec:
      containers:
      - name: eks-python
        image: 303a3ffe9e63dfaaac48bd1b935a568bbd26f59d9f6b15b3cade5a52ce36b19b
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eks-python
spec:
  type: LoadBalancer
  selector:
    app: eks-python
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
