apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks_python
spec:
  selector:
    matchLabels:
      app: eks_python
  replicas: 2
  template: 
    metadata:
      labels:
        myapp: eks_python
    spec:
      containers:
      - name: eks_python
        image: 8ec24d3f97c1632d6f640493722bc9c66ceb6f155dc04488720beb2e248a41db
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eks_python
spec:
  type: LoadBalancer
  selector:
    app: eks_python
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
